// utils/cities.js
export const cities = [
  { name: '臺北市', districts: [
      { name: '中正區', postalCode: '100' },
      { name: '大同區', postalCode: '103' },
      { name: '中山區', postalCode: '104' },
      { name: '松山區', postalCode: '105' },
      { name: '大安區', postalCode: '106' },
      { name: '萬華區', postalCode: '108' },
      { name: '信義區', postalCode: '110' },
      { name: '士林區', postalCode: '111' },
      { name: '北投區', postalCode: '112' },
      { name: '內湖區', postalCode: '114' },
      { name: '南港區', postalCode: '115' },
      { name: '文山區', postalCode: '116' }
  ]},
  { name: '新北市', districts: [
      { name: '板橋區', postalCode: '220' },
      { name: '三重區', postalCode: '241' },
      { name: '中和區', postalCode: '235' },
      { name: '永和區', postalCode: '234' },
      { name: '新莊區', postalCode: '242' },
      { name: '新店區', postalCode: '231' },
      { name: '樹林區', postalCode: '238' },
      { name: '鶯歌區', postalCode: '239' },
      { name: '三峽區', postalCode: '237' },
      { name: '淡水區', postalCode: '251' },
      { name: '汐止區', postalCode: '221' },
      { name: '瑞芳區', postalCode: '224' },
      { name: '土城區', postalCode: '236' },
      { name: '蘆洲區', postalCode: '247' },
      { name: '五股區', postalCode: '248' },
      { name: '泰山區', postalCode: '243' },
      { name: '林口區', postalCode: '244' },
      { name: '深坑區', postalCode: '222' },
      { name: '石碇區', postalCode: '223' },
      { name: '坪林區', postalCode: '232' },
      { name: '三芝區', postalCode: '252' },
      { name: '石門區', postalCode: '253' },
      { name: '八里區', postalCode: '249' },
      { name: '平溪區', postalCode: '226' },
      { name: '雙溪區', postalCode: '227' },
      { name: '貢寮區', postalCode: '228' },
      { name: '金山區', postalCode: '208' },
      { name: '萬里區', postalCode: '207' },
      { name: '烏來區', postalCode: '233' }
  ]},
  { name: '桃園市', districts: [
      { name: '桃園區', postalCode: '330' },
      { name: '中壢區', postalCode: '320' },
      { name: '大溪區', postalCode: '335' },
      { name: '楊梅區', postalCode: '326' },
      { name: '蘆竹區', postalCode: '338' },
      { name: '大園區', postalCode: '337' },
      { name: '龜山區', postalCode: '333' },
      { name: '八德區', postalCode: '334' },
      { name: '龍潭區', postalCode: '325' },
      { name: '平鎮區', postalCode: '324' },
      { name: '新屋區', postalCode: '327' },
      { name: '觀音區', postalCode: '328' },
      { name: '復興區', postalCode: '336' }
  ]},
  { name: '臺中市', districts: [
      { name: '中區', postalCode: '400' },
      { name: '東區', postalCode: '401' },
      { name: '南區', postalCode: '402' },
      { name: '西區', postalCode: '403' },
      { name: '北區', postalCode: '404' },
      { name: '北屯區', postalCode: '406' },
      { name: '西屯區', postalCode: '407' },
      { name: '南屯區', postalCode: '408' },
      { name: '太平區', postalCode: '411' },
      { name: '大里區', postalCode: '412' },
      { name: '霧峰區', postalCode: '413' },
      { name: '烏日區', postalCode: '414' },
      { name: '豐原區', postalCode: '420' },
      { name: '后里區', postalCode: '421' },
      { name: '石岡區', postalCode: '422' },
      { name: '東勢區', postalCode: '423' },
      { name: '和平區', postalCode: '424' },
      { name: '新社區', postalCode: '426' },
      { name: '潭子區', postalCode: '427' },
      { name: '大雅區', postalCode: '428' },
      { name: '神岡區', postalCode: '429' },
      { name: '大肚區', postalCode: '432' },
      { name: '沙鹿區', postalCode: '433' },
      { name: '龍井區', postalCode: '434' },
      { name: '梧棲區', postalCode: '435' },
      { name: '清水區', postalCode: '436' },
      { name: '大甲區', postalCode: '437' },
      { name: '外埔區', postalCode: '438' },
      { name: '大安區', postalCode: '439' }
  ]},
  { name: '臺南市', districts: [
      { name: '中西區', postalCode: '700' },
      { name: '東區', postalCode: '701' },
      { name: '南區', postalCode: '702' },
      { name: '北區', postalCode: '704' },
      { name: '安平區', postalCode: '708' },
      { name: '安南區', postalCode: '709' },
      { name: '永康區', postalCode: '710' },
      { name: '歸仁區', postalCode: '711' },
      { name: '新化區', postalCode: '712' },
      { name: '左鎮區', postalCode: '713' },
      { name: '玉井區', postalCode: '714' },
      { name: '楠西區', postalCode: '715' },
      { name: '南化區', postalCode: '716' },
      { name: '仁德區', postalCode: '717' },
      { name: '關廟區', postalCode: '718' },
      { name: '龍崎區', postalCode: '719' },
      { name: '官田區', postalCode: '720' },
      { name: '麻豆區', postalCode: '721' },
      { name: '佳里區', postalCode: '722' },
      { name: '西港區', postalCode: '723' },
      { name: '七股區', postalCode: '724' },
      { name: '將軍區', postalCode: '725' },
      { name: '學甲區', postalCode: '726' },
      { name: '北門區', postalCode: '727' },
      { name: '新營區', postalCode: '730' },
      { name: '後壁區', postalCode: '731' },
      { name: '白河區', postalCode: '732' },
      { name: '東山區', postalCode: '733' },
      { name: '六甲區', postalCode: '734' },
      { name: '下營區', postalCode: '735' },
      { name: '柳營區', postalCode: '736' },
      { name: '鹽水區', postalCode: '737' },
      { name: '善化區', postalCode: '741' },
      { name: '大內區', postalCode: '742' },
      { name: '山上區', postalCode: '743' },
      { name: '新市區', postalCode: '744' },
      { name: '安定區', postalCode: '745' }
  ]},
  { name: '高雄市', districts: [
      { name: '新興區', postalCode: '800' },
      { name: '前金區', postalCode: '801' },
      { name: '苓雅區', postalCode: '802' },
      { name: '鹽埕區', postalCode: '803' },
      { name: '鼓山區', postalCode: '804' },
      { name: '旗津區', postalCode: '805' },
      { name: '前鎮區', postalCode: '806' },
      { name: '三民區', postalCode: '807' },
      { name: '楠梓區', postalCode: '811' },
      { name: '小港區', postalCode: '812' },
      { name: '左營區', postalCode: '813' },
      { name: '仁武區', postalCode: '814' },
      { name: '大社區', postalCode: '815' },
      { name: '岡山區', postalCode: '820' },
      { name: '路竹區', postalCode: '821' },
      { name: '阿蓮區', postalCode: '822' },
      { name: '田寮區', postalCode: '823' },
      { name: '燕巢區', postalCode: '824' },
      { name: '橋頭區', postalCode: '825' },
      { name: '梓官區', postalCode: '826' },
      { name: '彌陀區', postalCode: '827' },
      { name: '永安區', postalCode: '828' },
      { name: '湖內區', postalCode: '829' },
      { name: '鳳山區', postalCode: '830' },
      { name: '大寮區', postalCode: '831' },
      { name: '林園區', postalCode: '832' },
      { name: '鳥松區', postalCode: '833' },
      { name: '大樹區', postalCode: '840' },
      { name: '旗山區', postalCode: '842' },
      { name: '美濃區', postalCode: '843' },
      { name: '六龜區', postalCode: '844' },
      { name: '內門區', postalCode: '845' },
      { name: '杉林區', postalCode: '846' },
      { name: '甲仙區', postalCode: '847' },
      { name: '桃源區', postalCode: '848' },
      { name: '那瑪夏區', postalCode: '849' },
      { name: '茂林區', postalCode: '851' },
      { name: '茄萣區', postalCode: '852' }
  ]},
  { name: '基隆市', districts: [
      { name: '中正區', postalCode: '202' },
      { name: '七堵區', postalCode: '206' },
      { name: '暖暖區', postalCode: '205' },
      { name: '仁愛區', postalCode: '200' },
      { name: '中山區', postalCode: '203' },
      { name: '安樂區', postalCode: '204' },
      { name: '信義區', postalCode: '201' }
  ]},
  { name: '新竹市', districts: [
      { name: '東區', postalCode: '300' },
      { name: '北區', postalCode: '300' },
      { name: '香山區', postalCode: '300' }
  ]},
  { name: '嘉義市', districts: [
      { name: '東區', postalCode: '600' },
      { name: '西區', postalCode: '600' }
  ]},
  { name: '新竹縣', districts: [
      { name: '竹北市', postalCode: '302' },
      { name: '竹東鎮', postalCode: '310' },
      { name: '新埔鎮', postalCode: '305' },
      { name: '關西鎮', postalCode: '306' },
      { name: '湖口鄉', postalCode: '303' },
      { name: '新豐鄉', postalCode: '304' },
      { name: '芎林鄉', postalCode: '307' },
      { name: '橫山鄉', postalCode: '312' },
      { name: '北埔鄉', postalCode: '314' },
      { name: '寶山鄉', postalCode: '308' },
      { name: '峨眉鄉', postalCode: '315' },
      { name: '尖石鄉', postalCode: '313' },
      { name: '五峰鄉', postalCode: '311' }
  ]},
  { name: '苗栗縣', districts: [
      { name: '苗栗市', postalCode: '360' },
      { name: '苑裡鎮', postalCode: '358' },
      { name: '通霄鎮', postalCode: '357' },
      { name: '竹南鎮', postalCode: '350' },
      { name: '頭份市', postalCode: '351' },
      { name: '後龍鎮', postalCode: '356' },
      { name: '卓蘭鎮', postalCode: '369' },
      { name: '大湖鄉', postalCode: '364' },
      { name: '公館鄉', postalCode: '363' },
      { name: '銅鑼鄉', postalCode: '366' },
      { name: '南庄鄉', postalCode: '353' },
      { name: '頭屋鄉', postalCode: '362' },
      { name: '三義鄉', postalCode: '367' },
      { name: '西湖鄉', postalCode: '368' },
      { name: '造橋鄉', postalCode: '361' },
      { name: '三灣鄉', postalCode: '352' },
      { name: '獅潭鄉', postalCode: '354' },
      { name: '泰安鄉', postalCode: '365' }
  ]},
  { name: '彰化縣', districts: [
      { name: '彰化市', postalCode: '500' },
      { name: '鹿港鎮', postalCode: '505' },
      { name: '和美鎮', postalCode: '508' },
      { name: '線西鄉', postalCode: '507' },
      { name: '伸港鄉', postalCode: '509' },
      { name: '福興鄉', postalCode: '506' },
      { name: '秀水鄉', postalCode: '504' },
      { name: '花壇鄉', postalCode: '503' },
      { name: '芬園鄉', postalCode: '502' },
      { name: '員林市', postalCode: '510' },
      { name: '溪湖鎮', postalCode: '514' },
      { name: '田中鎮', postalCode: '520' },
      { name: '大村鄉', postalCode: '515' },
      { name: '埔鹽鄉', postalCode: '516' },
      { name: '埔心鄉', postalCode: '513' },
      { name: '永靖鄉', postalCode: '512' },
      { name: '社頭鄉', postalCode: '511' },
      { name: '二水鄉', postalCode: '530' },
      { name: '北斗鎮', postalCode: '521' },
      { name: '二林鎮', postalCode: '526' },
      { name: '田尾鄉', postalCode: '522' },
      { name: '埤頭鄉', postalCode: '523' },
      { name: '芳苑鄉', postalCode: '528' },
      { name: '大城鄉', postalCode: '527' },
      { name: '竹塘鄉', postalCode: '525' },
      { name: '溪州鄉', postalCode: '524' }
  ]},
  
  { name: '臺南市', districts: [
      { name: '中西區', postalCode: '700' },
      { name: '東區', postalCode: '701' },
      { name: '南區', postalCode: '702' },
      { name: '北區', postalCode: '704' },
      { name: '安平區', postalCode: '708' },
      { name: '安南區', postalCode: '709' },
      { name: '永康區', postalCode: '710' },
      { name: '歸仁區', postalCode: '711' },
      { name: '新化區', postalCode: '712' },
      { name: '左鎮區', postalCode: '713' },
      { name: '玉井區', postalCode: '714' },
      { name: '楠西區', postalCode: '715' },
      { name: '南化區', postalCode: '716' },
      { name: '仁德區', postalCode: '717' },
      { name: '關廟區', postalCode: '718' },
      { name: '龍崎區', postalCode: '719' },
      { name: '官田區', postalCode: '720' },
      { name: '麻豆區', postalCode: '721' },
      { name: '佳里區', postalCode: '722' },
      { name: '西港區', postalCode: '723' },
      { name: '七股區', postalCode: '724' },
      { name: '將軍區', postalCode: '725' },
      { name: '學甲區', postalCode: '726' },
      { name: '北門區', postalCode: '727' },
      { name: '新營區', postalCode: '730' },
      { name: '後壁區', postalCode: '731' },
      { name: '白河區', postalCode: '732' },
      { name: '東山區', postalCode: '733' },
      { name: '六甲區', postalCode: '734' },
      { name: '下營區', postalCode: '735' },
      { name: '柳營區', postalCode: '736' },
      { name: '鹽水區', postalCode: '737' },
      { name: '善化區', postalCode: '741' },
      { name: '大內區', postalCode: '742' },
      { name: '山上區', postalCode: '743' },
      { name: '新市區', postalCode: '744' },
      { name: '安定區', postalCode: '745' }
  ]},
  { name: '高雄市', districts: [
      { name: '新興區', postalCode: '800' },
      { name: '前金區', postalCode: '801' },
      { name: '苓雅區', postalCode: '802' },
      { name: '鹽埕區', postalCode: '803' },
      { name: '鼓山區', postalCode: '804' },
      { name: '旗津區', postalCode: '805' },
      { name: '前鎮區', postalCode: '806' },
      { name: '三民區', postalCode: '807' },
      { name: '楠梓區', postalCode: '811' },
      { name: '小港區', postalCode: '812' },
      { name: '左營區', postalCode: '813' },
      { name: '仁武區', postalCode: '814' },
      { name: '大社區', postalCode: '815' },
      { name: '岡山區', postalCode: '820' },
      { name: '路竹區', postalCode: '821' },
      { name: '阿蓮區', postalCode: '822' },
      { name: '田寮區', postalCode: '823' },
      { name: '燕巢區', postalCode: '824' },
      { name: '橋頭區', postalCode: '825' },
      { name: '梓官區', postalCode: '826' },
      { name: '彌陀區', postalCode: '827' },
      { name: '永安區', postalCode: '828' },
      { name: '湖內區', postalCode: '829' },
      { name: '鳳山區', postalCode: '830' },
      { name: '大寮區', postalCode: '831' },
      { name: '林園區', postalCode: '832' },
      { name: '鳥松區', postalCode: '833' },
      { name: '大樹區', postalCode: '840' },
      { name: '旗山區', postalCode: '842' },
      { name: '美濃區', postalCode: '843' },
      { name: '六龜區', postalCode: '844' },
      { name: '內門區', postalCode: '845' },
      { name: '杉林區', postalCode: '846' },
      { name: '甲仙區', postalCode: '847' },
      { name: '桃源區', postalCode: '848' },
      { name: '那瑪夏區', postalCode: '849' },
      { name: '茂林區', postalCode: '851' },
      { name: '茄萣區', postalCode: '852' }
  ]},
  { name: '基隆市', districts: [
      { name: '中正區', postalCode: '202' },
      { name: '七堵區', postalCode: '206' },
      { name: '暖暖區', postalCode: '205' },
      { name: '仁愛區', postalCode: '200' },
      { name: '中山區', postalCode: '203' },
      { name: '安樂區', postalCode: '204' },
      { name: '信義區', postalCode: '201' }
  ]},
  { name: '新竹市', districts: [
      { name: '東區', postalCode: '300' },
      { name: '北區', postalCode: '300' },
      { name: '香山區', postalCode: '300' }
  ]},
  { name: '嘉義市', districts: [
      { name: '東區', postalCode: '600' },
      { name: '西區', postalCode: '600' }
  ]},
  { name: '新竹縣', districts: [
      { name: '竹北市', postalCode: '302' },
      { name: '竹東鎮', postalCode: '310' },
      { name: '新埔鎮', postalCode: '305' },
      { name: '關西鎮', postalCode: '306' },
      { name: '湖口鄉', postalCode: '303' },
      { name: '新豐鄉', postalCode: '304' },
      { name: '芎林鄉', postalCode: '307' },
      { name: '橫山鄉', postalCode: '312' },
      { name: '北埔鄉', postalCode: '314' },
      { name: '寶山鄉', postalCode: '308' },
      { name: '峨眉鄉', postalCode: '315' },
      { name: '尖石鄉', postalCode: '313' },
      { name: '五峰鄉', postalCode: '311' }
  ]},
  { name: '苗栗縣', districts: [
      { name: '苗栗市', postalCode: '360' },
      { name: '苑裡鎮', postalCode: '358' },
      { name: '通霄鎮', postalCode: '357' },
      { name: '竹南鎮', postalCode: '350' },
      { name: '頭份市', postalCode: '351' },
      { name: '後龍鎮', postalCode: '356' },
      { name: '卓蘭鎮', postalCode: '369' },
      { name: '大湖鄉', postalCode: '364' },
      { name: '公館鄉', postalCode: '363' },
      { name: '銅鑼鄉', postalCode: '366' },
      { name: '南庄鄉', postalCode: '353' },
      { name: '頭屋鄉', postalCode: '362' },
      { name: '三義鄉', postalCode: '367' },
      { name: '西湖鄉', postalCode: '368' },
      { name: '造橋鄉', postalCode: '361' },
      { name: '三灣鄉', postalCode: '352' },
      { name: '獅潭鄉', postalCode: '354' },
      { name: '泰安鄉', postalCode: '365' }
  ]},
  { name: '彰化縣', districts: [
      { name: '彰化市', postalCode: '500' },
      { name: '鹿港鎮', postalCode: '505' },
      { name: '和美鎮', postalCode: '508' },
      { name: '線西鄉', postalCode: '507' },
      { name: '伸港鄉', postalCode: '509' },
      { name: '福興鄉', postalCode: '506' },
      { name: '秀水鄉', postalCode: '504' },
      { name: '花壇鄉', postalCode: '503' },
      { name: '芬園鄉', postalCode: '502' },
      { name: '員林市', postalCode: '510' },
      { name: '溪湖鎮', postalCode: '514' },
      { name: '田中鎮', postalCode: '520' },
      { name: '大村鄉', postalCode: '515' },
      { name: '埔鹽鄉', postalCode: '516' },
      { name: '埔心鄉', postalCode: '513' },
      { name: '永靖鄉', postalCode: '512' },
      { name: '社頭鄉', postalCode: '511' },
      { name: '二水鄉', postalCode: '530' },
      { name: '北斗鎮', postalCode: '521' },
      { name: '二林鎮', postalCode: '526' },
      { name: '田尾鄉', postalCode: '522' },
      { name: '埤頭鄉', postalCode: '523' },
      { name: '芳苑鄉', postalCode: '528' },
      { name: '大城鄉', postalCode: '527' },
      { name: '竹塘鄉', postalCode: '525' },
      { name: '溪州鄉', postalCode: '524' }
  ]},
]